name: Build kwin-x11 .deb for Termux (aarch64)

on:
  workflow_dispatch:

jobs:
  build-kwin-x11:
    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          git cmake ninja-build g++-aarch64-linux-gnu \
          qt6-base-dev qt6-declarative-dev qt6-tools-dev qt6-tools-dev-tools \
          extra-cmake-modules kdoctools-dev \
          gettext libxml2-dev libxslt1-dev \
          libkf5archive-dev libkf5i18n-dev \
          libxcb1-dev libx11-dev libxrender-dev \
          libepoxy-dev libwayland-dev dpkg-dev

    - name: Checkout kwin-x11 source
      run: |
        git clone https://github.com/KDE/kwin-x11.git
        cd kwin-x11
        git checkout v6.4.2

    - name: Configure and build
      run: |
        cd kwin-x11
        mkdir build && cd build
        cmake .. \
          -DCMAKE_SYSTEM_NAME=Linux \
          -DCMAKE_SYSTEM_PROCESSOR=aarch64 \
          -DCMAKE_INSTALL_PREFIX=/usr \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_C_COMPILER=aarch64-linux-gnu-gcc \
          -DCMAKE_CXX_COMPILER=aarch64-linux-gnu-g++ \
          -DKDE_INSTALL_USE_QT_SYS_PATHS=ON
        cmake --build . -j$(nproc)
        DESTDIR=$HOME/kwin-x11-pkg cmake --install .

    - name: Build .deb package
      run: |
        mkdir -p $HOME/kwin-x11-pkg/DEBIAN

        cat <<EOF > $HOME/kwin-x11-pkg/DEBIAN/control
        Package: kwin-x11
        Version: 6.4.2
        Architecture: aarch64
        Maintainer: you@example.com
        Description: KDE kwin-x11 window manager (built for Termux)
        EOF

        dpkg-deb --build $HOME/kwin-x11-pkg kwin-x11-6.4.2-aarch64.deb

    - name: Upload .deb artifact
      uses: actions/upload-artifact@v4
      with:
        name: kwin-x11-deb
        path: kwin-x11-6.4.2-aarch64.deb
