name: Build kwin-x11 for Termux (aarch64)

on:
  workflow_dispatch:

jobs:
  build-kwin:
    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y git cmake ninja-build g++-aarch64-linux-gnu \
          qt6-base-dev qt6-declarative-dev qt6-tools-dev qt6-tools-dev-tools \
          extra-cmake-modules gettext libxml2-dev libxslt1-dev \
          libkf5archive-dev libkf5i18n-dev kdoctools-dev

    - name: Checkout kwin source
      run: |
        git clone https://invent.kde.org/plasma/kwin.git
        cd kwin
        git checkout v6.4.2

    - name: Configure and build
      run: |
        cd kwin
        mkdir build && cd build
        cmake .. \
          -DCMAKE_SYSTEM_NAME=Linux \
          -DCMAKE_SYSTEM_PROCESSOR=aarch64 \
          -DCMAKE_INSTALL_PREFIX=$HOME/kwin-out \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_C_COMPILER=aarch64-linux-gnu-gcc \
          -DCMAKE_CXX_COMPILER=aarch64-linux-gnu-g++ \
          -DKDE_INSTALL_USE_QT_SYS_PATHS=ON
        cmake --build . -j$(nproc)
        cmake --install .

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: kwin-aarch64
        path: ~/kwin-out
